FROM docker.elastic.co/logstash/logstash:5.6.3

COPY logstash.conf /usr/share/logstash/pipeline/logstash.conf
#RUN echo "xpack.monitoring.elasticsearch.url: http://elasticsearch:9200" > /usr/share/logstash/config/logstash.yml
