version: '3'
services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:5.6.3"
    environment:
      - discovery.type=single-node
  fpm:
    build:
      context: fpm-config
    volumes:
    - ./www:/app
  httpd:
    image: "httpd:latest"
    volumes:
    - ./httpd-config:/usr/local/apache2/conf
    - ./www:/usr/local/apache2/htdocs/
    - apachelogs:/usr/local/apache2/logs/
  redis:
    image: "redis:alpine"
  logstash:
    build:
      context: logstash-config
    volumes:
      - apachelogs:/httpdlogs/
  kibana:
    image: "docker.elastic.co/kibana/kibana:5.6.3"
    ports:
      - "5601:5601"
  lb:
    image: dockercloud/haproxy
    links:
      - httpd
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
volumes:
  apachelogs:
